/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as Modulo2RouteImport } from './routes/modulo-2'
import { Route as Modulo1RouteImport } from './routes/modulo-1'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo2Route = Modulo2RouteImport.update({
  id: '/modulo-2',
  path: '/modulo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Modulo1Route = Modulo1RouteImport.update({
  id: '/modulo-1',
  path: '/modulo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/glossario': typeof GlossarioRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/glossario': typeof GlossarioRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/glossario': typeof GlossarioRoute
  '/modulo-1': typeof Modulo1Route
  '/modulo-2': typeof Modulo2Route
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/glossario'
    | '/modulo-1'
    | '/modulo-2'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biblioteca' | '/glossario' | '/modulo-1' | '/modulo-2' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/glossario'
    | '/modulo-1'
    | '/modulo-2'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  GlossarioRoute: typeof GlossarioRoute
  Modulo1Route: typeof Modulo1Route
  Modulo2Route: typeof Modulo2Route
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-2': {
      id: '/modulo-2'
      path: '/modulo-2'
      fullPath: '/modulo-2'
      preLoaderRoute: typeof Modulo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-1': {
      id: '/modulo-1'
      path: '/modulo-1'
      fullPath: '/modulo-1'
      preLoaderRoute: typeof Modulo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  GlossarioRoute: GlossarioRoute,
  Modulo1Route: Modulo1Route,
  Modulo2Route: Modulo2Route,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
